import { HeaderComponent } from "./components/headerComponent.js";
import { render, RenderPosition } from "./render.js";
import { FormAddTaskComponent } from "./components/addTaskComponent.js";
import { ListBoardComponent } from "./components/listBoardContainer.js";
const bodyElement = document.querySelector(".board-app");
const addTaskElement = document.querySelector(".addtask-app");
const boardElement = document.querySelector(".board-app__list");
render(new HeaderComponent(), bodyElement, RenderPosition.BEFOREBEGIN);
render(new FormAddTaskComponent(), addTaskElement);
render(new ListBoardComponent(), boardElement);
